import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import { ReactQueryClientProvider } from "@/store/reactQuery/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={`${inter.className} bg-gradient-to-r from-cyan-500 to-blue-500 	`}
        >
          <Header />
          {children}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
