import type { Metadata } from "next";
import Header from "@/components/header/Header";
import { ReactQueryClientProvider } from "@/store/reactQuery/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={`bg-[#FFE4E3]`}>
          <Toaster
            toastOptions={{
              className: "",
              style: {
                border: "1px solid #713200",
                padding: "16px",
                color: "#713200",
              },
            }}
          />
          <Header />
          {children}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
